inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1.0
  NewCops: enable
  Exclude:
    - '*.rb'
    <% `git status --ignored --porcelain`.lines.grep(/^!! /).each do |path| %>
    - <%= path.sub(/^!! /, '').sub(/\/$/, '/**/*') %>
    <% end %>

Gemspec/RequireMFA:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false

Style/CaseEquality:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
  EnforcedStyle: template
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/NumericPredicate:
  EnforcedStyle: comparison
Style/PreferredHashMethods:
  EnforcedStyle: verbose
Style/SafeNavigation:
  Enabled: false
Style/SpecialGlobalVars:
  RequireEnglish: false
  EnforcedStyle: use_perl_names
