{
  "vpsfree_cz" = {
    targets = [ "https://vpsfree.cz/prihlaska/fyzicka-osoba/" ];
    host = "vpsfree.cz";
    bodyMatches = [ "vpsFree\\.cz \\| Přihláška" ];
    labels = {
      alias = "vpsfree.cz";
      type = "vpsfree-web";
    };
  };

  "vpsfree_org" = {
    targets = [ "https://vpsfree.org/registration/fyzicka-osoba/" ];
    host = "vpsfree.org";
    bodyMatches = [ "vpsFree\\.cz \\| Registration" ];
    labels = {
      alias = "vpsfree.org";
      type = "vpsfree-web";
    };
  };

  "api_vpsfree_cz" = {
    targets = [ "https://api.vpsfree.cz/" ];
    host = "api.vpsfree.cz";
    bodyMatches = [ "Generated by .*HaveAPI" ];
    labels = {
      alias = "api.vpsfree.cz";
      type = "vpsadmin-api";
    };
  };

  "console_vpsfree_cz" = {
    targets = [ "https://console.vpsfree.cz/vzconsole.js" ];
    host = "console.vpsfree.cz";
    bodyMatches = [ "Monitoring checks this file" ];
    labels = {
      alias = "vpsadmin.vpsfree.cz";
      type = "vpsadmin-console";
    };
  };

  "vpsadmin_vpsfree_cz" = {
    targets = [ "https://vpsadmin.vpsfree.cz/" ];
    host = "vpsadmin.vpsfree.cz";
    bodyMatches = [ "<title>[[:space:]]*vpsAdmin" ];
    labels = {
      alias = "vpsadmin.vpsfree.cz";
      type = "vpsadmin-webui";
    };
  };

  "status_vpsf_cz" = {
    targets = [ "https://status.vpsf.cz/" ];
    host = "status.vpsf.cz";
    bodyMatches = [ "vpsFree\\.cz Status" ];
    labels = {
      alias = "status.vpsf.cz";
      type = "vpsf-status";
    };
  };

  "kb_vpsfree_cz" = {
    targets = [ "https://kb.vpsfree.cz/" ];
    host = "kb.vpsfree.cz";
    bodyMatches = [ "Znalostní báze" ];
    labels = {
      alias = "kb.vpsfree.cz";
      type = "vpsfree-kb";
    };
  };

  "kb_vpsfree_org" = {
    targets = [ "https://kb.vpsfree.org/" ];
    host = "kb.vpsfree.org";
    bodyMatches = [ "Knowledge base" ];
    labels = {
      alias = "kb.vpsfree.org";
      type = "vpsfree-kb";
    };
  };

  "rubygems_vpsfree_cz" = {
    targets = [ "https://rubygems.vpsfree.cz/" ];
    host = "rubygems.vpsfree.cz";
    bodyMatches = [ "Gem in a Box" ];
    labels = {
      alias = "rubygems.vpsfree.cz";
      type = "vpsfree-rubygems";
    };
  };

  "paste_vpsfree_cz" = {
    targets = [ "https://paste.vpsfree.cz/" ];
    host = "paste.vpsfree.cz";
    bodyMatches = [ "Bepasty" ];
    labels = {
      alias = "paste.vpsfree.cz";
      type = "vpsfree-paste";
    };
  };

  "discourse_vpsfree_cz" = {
    targets = [ "https://discourse.vpsfree.cz/" ];
    host = "discourse.vpsfree.cz";
    bodyMatches = [ "vpsFree\\.cz Discourse" ];
    labels = {
      alias = "discourse.vpsfree.cz";
      type = "vpsfree-discourse";
    };
  };

  "munin_vpsfree_cz" = {
    targets = [ "https://munin.vpsfree.cz/" ];
    host = "munin.vpsfree.cz";
    bodyMatches = [ "Auto-generated by Munin" ];
    labels = {
      alias = "munin.vpsfree.cz";
      type = "vpsfree-munin";
    };
  };

  "grafana_prg_vpsfree_cz" = {
    targets = [ "https://grafana.prg.vpsfree.cz/" ];
    host = "grafana.prg.vpsfree.cz";
    bodyMatches = [ "<title>Grafana</title>" ];
    labels = {
      alias = "grafana.prg.vpsfree.cz";
      type = "vpsfree-grafana";
    };
  };
}
