[
  ./containers/int.bb.master/module.nix
  ./containers/int.bb.nixos01/module.nix
  ./containers/int.bb.nixos02/module.nix
  ./containers/int.cache/module.nix
  ./containers/int.images/module.nix
  ./containers/int.iso/module.nix
  ./containers/int.www/module.nix
  ./containers/proxy/module.nix
]
